### PR TITLE
Some cleanup for production run

### PR DESCRIPTION
**Pull request by bellemae**
Main changes:
- switch x,y usage to y,x in gridspec creation
- get band names from config file
- update wofs-summary product name
- include product definitions for ancillary datasets

### CODE REVIEW

**Review by ashoka1234 — COMMENTED** [review]
All good except the nodata values of float32 bands of dsm and modis probably not 255? Could it be -1?

**Comment by Kirill888** [comment]
`float32` shouldn't need `nodata`, it already supports `NaN`, is this data we produced, or external source? Also schema demands that `nodata` fields be present, but also allows `NaN`, which should be default for `float{32|64}` types.

**Comment by ashoka1234** [comment]
I think some of these we have produced with different scaling and cutoffs. It seems like `255` was interpreted as out of range even for `float32`!

**Comment by bellemae** [comment]
These are datasets from an external source, used in calculating the confidence layer. The nodata values here are based on what is expected in the existing confidence code.

**Pull request merged**
